name: 'build-push-image'
description: "Build and Push docker images"

inputs:
  IMAGE_TAG:
    description: "TAG for the docker image"
    required: true
  IMAGE_NAME:
    description: "Name of the docker image in the Container registry"
    required: true
  GCP_PROJECT_ID:
    description: 'GCP project ID'
    required: true
  DOCKERFILE_PATH:
    description: 'Path for the DOCKERFILE'
    required: true
  access_token:
    description: 'Registry Login token'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: 'docker/login-action@v1'
      with:
        registry: 'gcr.io' # or REGION-docker.pkg.dev
        username: 'oauth2accesstoken'
        password: '${{ inputs.access_token }}'

    - name: Build docker image
      shell: bash
      run:  docker build -t gcr.io/${{ inputs.GCP_PROJECT_ID }}/${{ inputs.IMAGE_NAME}}:${{ inputs.IMAGE_TAG }} ${{ inputs.DOCKERFILE_PATH }} 

    - name: Push to Google Container Registry
      shell: bash
      run:  docker push gcr.io/${{ inputs.GCP_PROJECT_ID }}/${{ inputs.IMAGE_NAME}}:${{ inputs.IMAGE_TAG }}
      

# runs:
#   using: 'composite'
#   steps:
#     - uses: actions/checkout@v2
    
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Build and push
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ${{ inputs.DOCKERFILE_PATH }}
#         push: true
#         tags: ${{ inputs.GCR_ADDRESS }}/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}